### ISSUE TITLE
Thoughts and Suggestions

### ISSUE THREAD

**Issue by saxamaphone69** [Catgrills/Pygmalion#1]
Good looking style(s) as always dude! Glad to see them on GitHub.

Was just going to suggest a few things:
  - instead of having `regexp("http://boards.4chan.org/BOARD/.*")` for every board; in your main part of the style, include the
```css
.fixed:root:not(.autohide):not(.bottom) .boardBanner {
        /** GENERAL/BANNER/CUSTOM **/
        margin-top: -6px;
        background-position: center !important;
        background-size: cover !important; 
        width: 101% !important;
        height: 150px !important;
        position: absolute !important;
        top: 30px !important;
    }
```

(without the `background` property), and then for each board you, you could just do:

```css
:root.fixed:not(.autohide):(.bottom) .board_BOARD .boardBanner {
  background-image: url('...');
}
```

as `.board_BOARD`, where `BOARD` is any board letter, is added to the `body`
in saying that, `.is_index` and `.is_thread` is also added to the `body` if you want specific styling for when in threads and on the index

 - also suggest not linking to imgur or other websites (mixed content warnings), and perhaps converting these to data URIs instead

**Comment by Catgrills** [comment]
Thanks for the feedback sax' ! For the banner I have to agree with you, I was just lazy I guess ~
For the pictures, what's the issue with imgur ? Haven't had any problems with it, that's why I kept it that way !

**Comment by saxamaphone69** [comment]
No issue with imgur. Since the main reason it's used is for icons, switching out the imgur request to a simple data URI saves a HTTP request/network hit. Browsing 4chan over HTTPS with pygmalion also gives those mixed content warnings I mentioned.

Just some passing thoughts upon initially seeing the userstyle. I've been doing this for way too long and put too much effort into making efficient and aesthetic for this bloody website. Just good to see someone else making something that isn't the typical "dark like my soul" stuff that most plebs use.

**Comment by Catgrills** [comment]
Oh, I see, I didn't see it that way ! Welp, even tho this script is quite simple I like it, and I assure you that yours is quite aesthetic and original, hope you'll work on others stuff in the future, I like your style !

**Comment by saxamaphone69** [comment]
Good to see a new refresh of Pygmalion!

 - consider using css custom properties/variables to manage colours and board banners
```css
/* set a default banner image for all boards */
:root {
  --banner: url('...');
}
/* set default banner styles for all boards */
.boardBanner {
  background-image: var(--banner) !important;
  background-position: cover;
}
/* override default banner image and replace with one for ck */
.board_ck .boardBanner {
  --banner: url('ck');
}
```
 - consider using an `@import` to include roboto and not worry about people having to download it (and potentially other fonts that are hosted externally)
```css
@import url('https://fonts.googleapis.com/css?family=Roboto');
```
 - load everything over `https` so that users browsing 4chan securely aren't at a disadvantage
```css
/* eg turn */
background: url("http://i.imgur.com/GYTIp7H.jpg") !important;
/* into */
background: url("https://i.imgur.com/GYTIp7H.jpg") !important;
```
 - people are inherently lazy, so the less steps to get them from where they are to what they want is best. what i mean by this, is consider supporting more 4chan X settings by default so things "just work"
 - in addition to this, is oneechan required? i think you can achieve the exact same userstyle without relying on another script (would require a rewrite)
 - consider running your css through a linter/formatter as there are a few errors/warnings
```css
/* double space between japanese text and !important */
font-family: "Roboto", "ぼくたちのゴシック２ボールド"  !important;
```
 - in addition to this, it appears pygmalion-z is actually copy-pasted **3** times? could also be why that one anon is having difficulty installing it
 - in addition to this, since it was copy-pasted several times, there are some missing closing brackets `}` that cause errors
 - consider removing all `@-moz-document regexp` declarations, as per my original comment, 4chan X gives you a class on `body` to determine where you are
```css
.is_index .board {
  /* will only affect the .board when on the index */
}
.is_thread .board {
  /* will only affect the .board when in a thread */
}
.board_g .board {
  /* will only affect the .board on /g/ */
}
.board_wg .board {
  /* will only affect the .board on/wg/ */
}
```
which means you would only require
```css
@-moz-document domain('boards.4chan.org') {
  .board {
    /* pygmalion.user.css */
  }
}
```
cause when you import into chrome it looks like this atm
![browser](https://user-images.githubusercontent.com/877480/27265064-b1f3849e-54d1-11e7-9be6-1f42988c851e.jpg)
